### ISSUE TITLE
Experiment Setting

### ISSUE THREAD

**Issue by willer-lu** [THU-KEG/KB-Plugin#1]
Hi!
What is the smallest gpu memory to reproduce your work?  
or 
which kind of GPU did you use?

**Comment by Neo-Zhangjiajie** [comment]
We use  80G A800 GPUs to train the models. I think 32G memory is enough since you just need to tune the LoRA modules.

**Comment by willer-lu** [comment]
Thanks.
One more question, is one single gpu(such as A100) enough?

**Comment by Neo-Zhangjiajie** [comment]
Yes, but it would cost more time than using multiple GPUs simultaneously.
