### ISSUE TITLE
About the number of generated source KBs

### ISSUE THREAD

**Issue by willer-lu** [THU-KEG/KB-Plugin#4]
If I change the number of generated source KBs, for example, from 16 to 8, does it means the 'BS' in _KB-Plugin/source_kqapro/sft_llama/process_pi_data.py_  ,  _KB-Plugin/source_kqapro/sft_llama/mix_pi_data.py_ and _KB-Plugin/source_kqapro/sft_llama/train_pi_plugin.sh_ should be set to 8?     
I wonder if there is some relation between these variables.     
In other words, if I change the number of source KBs from 16 to 8, when I train PI Plugin, which part of the codes should be changed?(Supposed that the files have been formed)

**Comment by Neo-Zhangjiajie** [comment]
Yes, you just need to change 'BS' in the 3 files you mentioned.
